/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:90e99890-98d0-40f0-ac9b-868263befd9b",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_7PetQLyMJ",
    "aws_user_pools_web_client_id": "329l2qkfk3uj7j8n3vm6vkjh5l",
    "oauth": {},
    "aws_user_files_s3_bucket": "academyexcellenceqstnimage115125-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
